# Generated by Django 2.0.6 on 2018-07-03 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('types', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seeking', models.IntegerField(default=0)),
                ('pauses', models.IntegerField(default=0)),
                ('replaycount', models.IntegerField(default=0)),
                ('types', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('gender', models.IntegerField(choices=[(1, 'F'), (2, 'M')])),
                ('age', models.IntegerField()),
                ('standard', models.IntegerField(choices=[(0, 'other'), (1, 'STD-I'), (2, 'STD-II'), (3, 'STD-III'), (4, 'STD-IV'), (5, 'STD-V'), (6, 'STD-VI'), (7, 'STD-VII'), (8, 'STD-VIII'), (9, 'STD-IX'), (10, 'STD-X'), (11, 'STD-XI'), (12, 'STD-XII')])),
                ('school_name', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
