# Generated by Django 2.0.6 on 2018-07-06 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seeking', models.IntegerField(default=0)),
                ('pauses', models.IntegerField(default=0)),
                ('replaycount', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
