# Generated by Django 2.0.6 on 2018-07-19 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ML', '0002_auto_20180706_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('basic', models.IntegerField(default=0)),
                ('intermediate', models.IntegerField(default=0)),
                ('advance', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
